### ISSUE TITLE
Which python version should I use?

### ISSUE THREAD

**Issue by KatanaNeko** [pagvac/dnsmap#2]
when i use python `3.11.9` and `3.12.6` ,it says
```shell
File "/opt/dnsmap/dnsmap.py", line 112
    <title>dnsmap/dnsmap.py at main · pagvac/dnsmap · Git</title>
                                    ^
SyntaxError: invalid character '·' (U+00B7)
```
when i use python `2.7.18` and `3.8.0` ,itsays
```shell
File "/opt/dnsmap/dnsmap.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```
`/opt/dnsmap` is where i store `dnsmap.py`.I am sorry i am not familiar with the English language and the use of python. Please tell me what I should do to solve it.

**Comment by pagvac** [comment]
@KatanaNeko did you save `dnsmap.py` as a webpage? There should be no HTML tags inside it. Try the following:

1. $ gh repo clone pagvac/dnsmap
2. $ python3 dnsmap/dnsmap.py github.com

**Comment by KatanaNeko** [comment]
Oh, I'm so sorry and thank you so much.😱😭😘
